### PR TITLE
Fix form elements resolution

### LINKED ISSUE #29: Failed to crawl page: undefined is not an object (evaluating 'f[name].length')
Some pages at my project doesn't crawls at all:(
For example: https://partners.bitrix24.com/application.php
Add a some debug to `page.onError` in `render.js`, launched the phantomjs, catched a JS error:

```
$ phantomjs ./renderer/resource/render.js https://partners.bitrix24.com/application.php | head -1 | python -mjson.tool
{
    "type": "js error",
    "errorString": "TypeError: undefined is not an object (evaluating 'f[name].length')",
    "trace": [
        {
            "file": "./extractors.js",
            "line": 327,
            "function": "getForm"
        },
        {
            "file": "",
            "line": 0,
            "function": "forEach"
        },
        {
            "file": "./extractors.js",
            "line": 441,
            "function": "extractRequests"
        },
        {
            "file": "./extractors.js",
            "line": 452,
            "function": "_gryffin_onMainFrameReady"
        },
        {
            "file": "phantomjs://webpage.evaluate()",
            "line": 3,
            "function": ""
        },
        {
            "file": "phantomjs://webpage.evaluate()",
            "line": 4,
            "function": ""
        }
    ],
    "msgType": "error",
    "signature": "==lXlKfYWch7H9VdJgPCmJ=="
}
```

Steps to reproduce:
- Testing page:

```
 $ http -b https://www.buglloc.com/static/gryffin/forms-unencoded-fields.html
<html>
<body>
<a href="/foo">foo</a>
<form name="with-query" action="/" method="post">
    <input type="text" name="foo[]" value="some" />
    <select name="bar[]">
        <option value="one">One</option>
        <option value="two">Two</option>
    </select>
    <input type="submit" name="save" value="Save">
</form>
</body>
</html>
```
- Launch pantomjs:

```
 $ phantomjs ./renderer/resource/render.js https://www.buglloc.com/static/gryffin/forms-unencoded-fields.html | head -1 | python -mjson.tool

{
    "response": {
        "headers": {[...]},
        "contentType": "text/html; charset=utf-8",
        "status": 200,
        "url": "https://www.buglloc.com/static/gryffin/forms-unencoded-fields.html",
        "body": "<html><head></head><body>\n<a href=\"/foo\">foo</a>\n<form name=\"with-query\" action=\"/\" method=\"post\">\n\t<input type=\"text\" name=\"foo[]\" value=\"some\">\n\t<select name=\"bar[]\">\n\t\t<option value=\"one\">One</option>\n\t\t<option value=\"two\">Two</option>\n\t</select>\n\t<input type=\"submit\" name=\"save\" value=\"Save\">\n</form>\n\n\n</body></html>",
        "details": {
            "links": [],
            "forms": []
        }
    },
    "elasped": 584,
    "ok": 1,
    "msgType": "domSteady",
    "signature": "==lXlKfYWch7H9VdJgPCmJ=="
}

```
- No links or forms in details

### PR DESCRIPTION
**Pull request by buglloc**
May resolve #29 :)
Original results:

```
 $ phantomjs ./renderer/resource/render.js https://www.buglloc.com/static/gryffin/forms-unencoded-fields.html | head -1 | python -mjson.tool

{
    "response": {
        "headers": {...},
        "contentType": "text/html; charset=utf-8",
        "status": 200,
        "url": "https://www.buglloc.com/static/gryffin/forms-unencoded-fields.html",
        "body": "<html><head></head><body>\n<a href=\"/foo\">foo</a>\n<form name=\"with-query\" action=\"/\" method=\"post\">\n\t<input type=\"text\" name=\"foo[]\" value=\"some\">\n\t<select name=\"bar[]\">\n\t\t<option value=\"one\">One</option>\n\t\t<option value=\"two\">Two</option>\n\t</select>\n\t<input type=\"submit\" name=\"save\" value=\"Save\">\n</form>\n\n\n</body></html>",
        "details": {
            "links": [],
            "forms": []
        }
    },
    "elasped": 586,
    "ok": 1,
    "msgType": "domSteady",
    "signature": "==lXlKfYWch7H9VdJgPCmJ=="
}
```

After apply this PR:

```
 $ phantomjs ./renderer/resource/render.js https://www.buglloc.com/static/gryffin/forms-unencoded-fields.html | head -1 | python -mjson.tool
{
    "response": {
        "headers": {...},
        "contentType": "text/html; charset=utf-8",
        "status": 200,
        "url": "https://www.buglloc.com/static/gryffin/forms-unencoded-fields.html",
        "body": "<html><head></head><body>\n<a href=\"/foo\">foo</a>\n<form name=\"with-query\" action=\"/\" method=\"post\">\n\t<input type=\"text\" name=\"foo[]\" value=\"some\">\n\t<select name=\"bar[]\">\n\t\t<option value=\"one\">One</option>\n\t\t<option value=\"two\">Two</option>\n\t</select>\n\t<input type=\"submit\" name=\"save\" value=\"Save\">\n</form>\n\n\n</body></html>",
        "details": {
            "links": [
                {
                    "text": "foo",
                    "url": "https://www.buglloc.com/foo"
                }
            ],
            "forms": [
                {
                    "data": "bar%5B%5D=one&foo%5B%5D=some&save=Save",
                    "dataType": {
                        "bar%5B%5D": "select-one",
                        "foo%5B%5D": "text",
                        "save": "submit"
                    },
                    "method": "post",
                    "url": "https://www.buglloc.com/"
                },
                {
                    "data": "bar%5B%5D=two&foo%5B%5D=some&save=Save",
                    "dataType": null,
                    "method": "post",
                    "url": "https://www.buglloc.com/"
                }
            ],
            "jsLinkFeedback": true
        }
    },
    "elasped": 580,
    "ok": 1,
    "msgType": "domSteady",
    "signature": "==lXlKfYWch7H9VdJgPCmJ=="
}
```

### CODE REVIEW

**Comment by adon-at-work** [comment]
Thanks for the bug hunting. But unfortunately this is NOT a good fix. 

Can you please replace `f[name]` with `f[input.name]` instead of `input`? and check if it can fundamentally solve your problem?

Main reason of your issue is because `name` (i.e., `bar%5B%5D`) is an URI encoded version of `input.name` (i.e., `bar[]`), as in
https://github.com/yahoo/gryffin/pull/30/files#diff-00c99a77228efa95757ceb327151661dR312 . This makes the form `f[name]` fails to get an array of same named elements.

Thanks! (or leave it for me to send a PR may be next week) :)

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by buglloc** [comment]
Can you explain why the use of `input` in this case is wrong?
Funny, but at first I did exactly as you mentioned (use `f[input.name]` instead of `input`). But then I can't understand the reasons for not using `input` and submit PR with `input` :)

I understand the reason of my issue, otherwise I would not make any patches.

> Can you please replace f[name] with f[input.name] instead of input? and check if it can fundamentally solve your problem?

Sure! I previously checked both version with `f[input.name]` and `input`.

**Comment by adon-at-work** [comment]
Given the following use case:

``` html
<form><input name=a type=radio value=M><input name=a type=radio value=F></form>
```

`f[input.name]` returns two input elements
`input` will return the element being iterated

**Comment by buglloc** [comment]
Oh, i see. I was wrong, thanks!

**Comment by adon-at-work** [comment]
No problem. Really thanks for hunting the bug. :+1:

**Comment by adon-at-work** [comment]
and I see another potential bug. it looks like you have a not-so-standard element like `<select type="select-one">` inside your form, which I didn't expect elements like select and textarea would have a type attribute. that makes `dataType` to see 'select-one' instead of 'select'. this won't kill gryffin for now, as it's not being really used I believe. better to separately set the type in those three if-else branches.

**Pull request closed without merging**
